server.port=0

spring.application.name=config-server
spring.profiles.active=native
spring.output.ansi.enabled=always
spring.cloud.config.server.native.search-locations=\
  classpath:config/telemetry/{application},\
  classpath:config/commerce/{application}, \
  classpath:config/infra/{application}

eureka.client.service-url.default-zone=http://localhost:8761/eureka/ 
