server.port=0

spring.application.name=warehouse
spring.config.import=configserver:
spring.cloud.config.fail-fast=true
spring.cloud.config.discovery.enabled=true
spring.cloud.config.discovery.service-id=config-server
spring.cloud.config.retry.use-random-policy=true
spring.cloud.config.retry.max-interval=6000

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.health-check.enabled=true
eureka.client.service-url.default-zone=http://localhost:8761/eureka